language: node_js
sudo: false
branches:
  only:
  - gh-pages
env:
  global:
  - URL="https://raw.githubusercontent.com/w3c/input-events/v1/W3CTRMANIFEST"
  - DECISION="https://lists.w3.org/Archives/Public/public-webapps/2014JulSep/0627.html"
script:
- echo "ok"
after_success:
- curl "https://labs.w3.org/echidna/api/request" --data "url=$URL" --data "decision=$DECISION" --data "token=$TOKENV1"
